/* eslint-disable no-undef */
import { Schema, model } from "mongoose";

const UserSchema = new Schema({
  user_id: { type: String, required: true, unique: true }, // It will be generated by system
  name: { type: String, required: true },
  date_of_birth: { type: Date },
  mobile_number: { type: Number },
  email: { type: String, required: true },
  gender: { type: String },
  favorite_hotels: [{ type: String }],
  country: { type: String },
});

export default model("User", UserSchema);
